Project init
codex-team/devops-toolbox-app pull request #1
Opened 2020-11-06 13:48 UTC by fabled228

Инициализировал проект, установил зависимости(электрон), в index.js добавил код простого приложения.

2020-11-06 13:56 UTC, Xemka requested changes

2020-11-06 13:56 UTC, Xemka commented on index.js
> +mainWindow.loadURL(`file://$${__dirname}/index.html`);
первый '$' не лишний?

2020-11-06 13:58 UTC, fabled228 commented on index.js
> +mainWindow.loadURL(`file://$${__dirname}/index.html`);
Лишний

2020-11-07 15:04 UTC, kebyo commented on .eslintrc
> +  ]
Лишний пробел в 3 строчке

2020-11-07 15:10 UTC, kebyo commented on .eslintrc
> +  ]
А нет

2020-11-07 15:10 UTC, kebyo approved these changes

2020-11-10 18:28 UTC, nikmel2803 approved these changes

2020-11-10 18:30 UTC, neSpecc approved these changes

2020-11-10 18:44 UTC, Xemka approved these changes

2020-11-10 18:44 UTC, merged