Added terminal icon
codex-team/devops-toolbox-app pull request #11
Opened 2020-12-02 18:09 UTC by fabled228

added svg for terminal

2020-12-03 05:27 UTC, neSpecc requested changes

2020-12-03 05:27 UTC, neSpecc commented on src/components/Server.vue
> +      <svg
иконки надо хранить отдельными файлами. Погугли, как во vue использовать svg-иконки

2020-12-03 17:58 UTC, ilyamore88 requested changes

2020-12-03 17:58 UTC, ilyamore88 commented on src/components/Server.vue
>    color: #ffffff;
Зачем задавать цвет текста для иконки? Там в svg уже есть `fill="#FFF"`

2020-12-03 18:02 UTC, ilyamore88 requested changes
По макету иконка по центру:
![image](https://user-images.githubusercontent.com/37909603/101069155-ad1cf280-35aa-11eb-8978-aa718f39db73.png)
У тебя же она практически на одном уровне с текстом:
![image](https://user-images.githubusercontent.com/37909603/101069249-ca51c100-35aa-11eb-8c57-f0c53abc7d51.png)

2020-12-06 10:45 UTC, ilyamore88 commented on package.json
> +    "vue-svg-loader": "^0.17.0-beta.2"
Может лучше подключить стабильную версию, а не бету?

2020-12-06 10:51 UTC, fabled228 commented on package.json
> +    "vue-svg-loader": "^0.17.0-beta.2"
У меня,вроде, не работало с vue 3 и не бетой, поэтому нашёл такое решение

2020-12-06 10:53 UTC, ilyamore88 commented on package.json
> +    "vue-svg-loader": "^0.17.0-beta.2"
Ок👌

2020-12-06 10:53 UTC, ilyamore88 approved these changes

2020-12-08 17:15 UTC, nikmel2803 commented on src/components/Server.vue
> +import terminalSvg from '../assets/terminal.svg';
по сути же это компонент получается, поэтому стоит назвать с большой буквы

2020-12-08 17:18 UTC, neSpecc approved these changes

2020-12-08 17:26 UTC, merged