Feature/icons
codex-team/devops-toolbox-app pull request #12
Opened 2020-12-09 14:17 UTC by fabled228

added hovers for titles

2020-12-09 14:31 UTC, ilyamore88 requested changes
При наведении у меня курсор для выделения текста, а не `pointer`. Hover не должен срабатывать ещё при наведении на иконку терминала?

2020-12-09 14:58 UTC, ilyamore88 commented on src/components/Server.vue
> +    &-clickable {
```suggestion
    &--clickable {
```

2020-12-09 15:13 UTC, ilyamore88 approved these changes

2020-12-14 17:25 UTC, neSpecc requested changes

2020-12-14 17:25 UTC, neSpecc commented on src/components/Server.vue
> +        class="server__header--clickable"
не по бэму

2020-12-14 17:25 UTC, neSpecc commented on src/styles/variables.css
> +  /*Text shadow*/
непонятное описание

2020-12-14 17:25 UTC, neSpecc commented on src/components/Server.vue
> +      align-items: center;
не по бэму

2020-12-14 17:42 UTC, fabled228 commented on src/components/Server.vue
> +        class="server__header--clickable"
server__header_clickable ?

2020-12-14 18:02 UTC, neSpecc commented on src/components/Server.vue
> +        class="server__header--clickable"
а почему не сделать кликабельным просто весь заголовок?

2020-12-15 19:56 UTC, fabled228 commented on src/components/Server.vue
> +        class="server__header--clickable"
мне сделать весь header просто кликабельным или как?

2020-12-15 23:22 UTC, fabled228 commented on src/styles/variables.css
> +  /*Text shadow*/
а как можно понятнее?

2020-12-17 12:27 UTC, neSpecc requested changes

2020-12-17 12:27 UTC, neSpecc commented on src/components/Server.vue
> +     text-shadow: 0 0 2px var(--color-box-shadow-white);
тут не нужна отдельная переменная, тк этот цвет зависит от цвета текста

```suggestion
     text-shadow: 0 0 2px color-mod(var(--color-text-main) alpha(30%))
```

2020-12-17 12:27 UTC, neSpecc commented on src/styles/variables.css
>    --color-text-header: #ffffff;
```suggestion
  --color-text-main: #ffffff;
```

2020-12-18 15:53 UTC, neSpecc approved these changes

2020-12-18 15:54 UTC, merged