Entry point refactoring
codex-team/devops-toolbox-app pull request #18
Opened 2020-12-17 11:48 UTC by fabled228

Created new files with menu&appWindow creating logic

2020-12-17 12:04 UTC, neSpecc requested changes

2020-12-17 12:04 UTC, neSpecc commented on src/utils/menu.ts
> +      label: 'About',
какой же это utils, если тут данные бизнес-логики лежат? Утилиты — это абстрактные методы, которые не привязаны к конкретному месту

2020-12-17 12:04 UTC, neSpecc commented on src/utils/AppWindow.ts
> +    height: 352,
если это `utils`, то тут не должно быть ничего захардкожено

2020-12-17 12:04 UTC, neSpecc commented on src/utils/AppWindow.ts
> +  const menu = createAppMenu();
хардкод

2020-12-17 12:04 UTC, neSpecc commented on src/utils/AppWindow.ts
> +  tray = new Tray(iconPath);
не относится к createWindow

2020-12-17 12:04 UTC, neSpecc commented on src/utils/AppWindow.ts
> + * Creating window
непонятное описание

2020-12-17 12:04 UTC, neSpecc commented on src/utils/AppWindow.ts
> + * Protocol name
описание дублирует название

2020-12-17 12:08 UTC, fabled228 commented on src/utils/menu.ts
> +      label: 'About',
я думал, что должны быть components, но там лежат .vue файлы. Туда их поместить по итогу?

2020-12-17 12:30 UTC, neSpecc commented on src/utils/menu.ts
> +      label: 'About',
нет. Не знаю куда

2020-12-20 14:58 UTC, ilyamore88 commented on src/utils/calculateBounds.ts
> + * @param x - x of mouse click
Пофикси док

2020-12-21 17:59 UTC, neSpecc requested changes

2020-12-21 17:59 UTC, neSpecc commented on src/appElements/menu.ts
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
давай назовем папку просто `classes`

2020-12-21 17:59 UTC, neSpecc commented on src/appElements/menu.ts
> +export default function createAppMenu(): Menu {
пусть тут будет класс 

```ts
export default class AppMenu {
  ///...
}
```

2020-12-21 17:59 UTC, neSpecc commented on src/appElements/tray.ts
> +  const menu = createAppMenu();
меню не должно вызываться отсюда, лучше передать onRightClick и снаружи вызвать меню.

2020-12-21 17:59 UTC, neSpecc commented on src/background.ts
> +let window;
не описано

2020-12-21 17:59 UTC, neSpecc commented on src/background.ts
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars-experimental
зачем эти игноры везде?

2020-12-21 17:59 UTC, neSpecc commented on src/background.ts
> +let tray;
не описанная переменная. И снова в глобальном скоупе. Суть рефакторинга — убрать все в скоуп класса

2020-12-21 17:59 UTC, neSpecc commented on src/utils/browserWindow.ts
> + * Creating BrowserWindow
не понятное описание

2020-12-21 17:59 UTC, neSpecc commented on src/utils/calculateBounds.ts
> + * Calculating Bounds for browserWindow
а как именно высчитываются координаты? Может эту логику описать тоже в доке?

2020-12-21 17:59 UTC, neSpecc commented on src/utils/browserWindow.ts
> +    await window.loadURL(`${protocolName}://./index.html`);
не думаю, что надо хардкодить шаблон для окна, это же утилита. С помощью нее разные окна должно быть можно создавать

2020-12-21 17:59 UTC, neSpecc commented on src/background.ts
>  app.on('activate', async () => {
по-прежнему в точке входа свалка. Где класс приложения?

2020-12-27 16:01 UTC, closed without merging