Build app
codex-team/devops-toolbox-app pull request #19
Opened 2020-12-17 18:21 UTC by talyguryn

2020-12-17 18:22 UTC, neSpecc requested changes
No description provided.

2020-12-17 18:27 UTC, neSpecc commented on package.json
> +  "main": "background.js",
name is not clear

2020-12-17 18:28 UTC, ilyamore88 requested changes

2020-12-17 18:28 UTC, ilyamore88 commented on src/background.ts
> +  // const iconName = process.platform === 'win32' ? 'icon.ico' : 'icon.icns';
Закомментированный код

2020-12-17 18:28 UTC, ilyamore88 commented on src/utils/logger.ts
> +// })
Закомментированный код

2020-12-17 18:28 UTC, ilyamore88 commented on src/utils/logger.ts
> +// };
И вот тут

2020-12-17 18:28 UTC, ilyamore88 commented on package.json
> +    "electron:generate-icons": "electron-icon-builder --input=./public/icon.png --output=build --flatten"
После каждого билда надо будет сгенерировать иконки?

2020-12-17 18:34 UTC, ilyamore88 commented
И надо ли коммитить папку `build` на github?

2020-12-18 14:47 UTC, talyguryn commented on package.json
> +    "electron:generate-icons": "electron-icon-builder --input=./public/icon.png --output=build --flatten"
на ci будут пересобираться перед каждым билдом. на локали можно будет сделать один раз. как хочешь

2020-12-18 14:48 UTC, talyguryn commented
> И надо ли коммитить папку `build` на github?

убрал

2020-12-18 15:37 UTC, talyguryn commented on package.json
> +  "main": "background.js",
this is the clearest name that would be. it is a base for background process. it is a good practise to name this file 'background'.

2020-12-18 15:38 UTC, ilyamore88 approved these changes

2020-12-18 15:47 UTC, neSpecc approved these changes

2020-12-18 15:49 UTC, merged