Update package.json
codex-team/devops-toolbox-app pull request #2
Opened 2020-11-12 18:08 UTC by fabled228

2020-11-13 18:18 UTC, neSpecc commented on src/App.vue
> +  color: #2c3e50;
вынести в переменную, в файл variables.pcss

2020-11-14 14:00 UTC, neSpecc requested changes

2020-11-14 14:00 UTC, neSpecc commented on babel.config.js
> +    '@vue/cli-plugin-babel/preset',
babel в этом проекте не нужен

2020-11-14 16:23 UTC, neSpecc commented on package.json
>      "@vue/cli-plugin-babel": "~4.5.0",
babel надо выпилить

2020-11-14 16:23 UTC, neSpecc commented on package.json
> +    "babel-eslint": "^10.1.0",
снова babel

2020-11-14 17:58 UTC, nikmel2803 commented on src/index.ts
> +// import electron from 'electron';
надо удалить, если он теперь не нужен

2020-11-14 17:58 UTC, nikmel2803 commented on src/background.ts
> + *
нету коммента

2020-11-14 17:58 UTC, nikmel2803 commented on src/background.ts
> +        .ELECTRON_NODE_INTEGRATION as unknown) as boolean,
странное приведение типов
может лучше написать !!process.env.ELECTRON_NODE_INTEGRATION чтобы был boolean

2020-11-14 17:58 UTC, nikmel2803 commented on src/background.ts
> +import { app, protocol, BrowserWindow } from 'electron';
непонятно что значит название файла. Если это теперь главный файл приложения, может назвать его index.ts?

2020-11-14 18:01 UTC, nikmel2803 commented on package.json
>      "electron": "^10.1.5",
в devDeps тоже есть электрон
надо оставить только тут

2020-11-14 18:39 UTC, neSpecc commented on src/index.ts
> +  // Create the browser window.
мы используем комменты в блочном стиле. Eslint должен это проверять

2020-11-14 18:54 UTC, neSpecc commented on src/index.ts
> +    createProtocol('app');
протокол можно вынести в константу, мы потом поменяем его на свой

2020-11-14 19:13 UTC, neSpecc commented on src/index.ts
> +const isDevelopment = process.env.NODE_ENV !== 'production';
константы надо описать и отделить от импортов пустой строкой

2020-11-14 20:30 UTC, kebyo reviewed
Добавь .editorconfig. Можешь взять из [api](https://github.com/codex-team/devops-toolbox-api/blob/main/.editorconfig)

2020-11-16 14:27 UTC, nikmel2803 approved these changes

2020-11-16 17:25 UTC, neSpecc approved these changes

2020-11-16 17:31 UTC, merged