Feature/interaction between frontend and api
codex-team/devops-toolbox-app pull request #23
Opened 2020-12-24 19:53 UTC by kebyo

Added interaction between frontend and API

2020-12-24 20:05 UTC, neSpecc requested changes

2020-12-24 20:05 UTC, neSpecc commented on src/types/service.ts
> +export default interface Workspace {
не совпадает с названием файла

2020-12-24 20:05 UTC, neSpecc commented on src/utils/protocol/types/responses/authorize.ts
> +  userToken?: string;
ты же токен в запросе передаешь, зачем его возвращать

2020-12-24 20:05 UTC, neSpecc commented on src/utils/protocol/types/requests/getWorkspaces.ts
> +  token: string;
token точно относится к воркспейсам?

2020-12-24 20:05 UTC, neSpecc commented on package.json
> +    "run:transport": "ts-node src/utils/protocol/transport.ts"
а зачема эта команда? это должно быть частью приложения

2020-12-24 20:44 UTC, ilyamore88 requested changes

2020-12-24 20:44 UTC, ilyamore88 commented on .env.example
> +VUE_APP_API_URL=ws://localhost:8080/client
```suggestion
VUE_APP_API_URL=ws://localhost:3000/client
```
Чтобы совпадало с .env.example в api.

2020-12-24 20:44 UTC, ilyamore88 commented on .env.example
> +# Authorization token
```suggestion
# Workspace authorization token
```

2020-12-24 20:44 UTC, ilyamore88 commented on tsconfig.json
> +    "src/**/**/*.ts",
Лишнее

2020-12-25 05:47 UTC, kebyo commented on src/utils/protocol/types/requests/getWorkspaces.ts
> +  token: string;
Ну так у нас же каждый воркспейс прикреплен к 1 `authToken`'у

2020-12-25 05:48 UTC, kebyo commented on package.json
> +    "run:transport": "ts-node src/utils/protocol/transport.ts"
Я тестил, забыл убрать

2020-12-25 21:22 UTC, neSpecc commented on src/utils/protocol/transport.ts
> +        switch (data.type) {
если тут бизнес-логика, то это не утилита

2020-12-25 21:22 UTC, neSpecc commented on src/utils/protocol/transport.ts
> +export function createClient (): CTProtoClient<AuthorizeMessagePayload, DevopsToolboxAuthData, ApiRequest, ApiResponse, ApiUpdate> {
доков нет

2020-12-25 21:22 UTC, neSpecc commented on src/utils/protocol/types/requests/getWorkspaces.ts
> +  token: string;
ну и что, ты же уже передал этот токен при авторизации.

2020-12-25 21:54 UTC, talyguryn requested changes

2020-12-25 21:54 UTC, talyguryn commented on .gitignore
> +package-lock.json
нельзя игнорить лок-файл. к тому же, у нас используется ярн в качестве менеджера пакетов. от него есть yarn.lock файл в репозитории.

установить ярн и использовать вместо npm можно командой `npm i -g yarn`

2020-12-25 21:54 UTC, talyguryn commented on src/config/index.ts
> +dotenv.config({ path: path.join(__dirname, '/../../.env') });
путь лучше указывать не слешами, а отдельными элементами через path.join
```suggestion
dotenv.config({ path: path.join(__dirname, '..', '..', '.env') });
```

2020-12-26 19:30 UTC, kebyo commented on src/config/index.ts
> +dotenv.config({ path: path.join(__dirname, '/../../.env') });
Почему?

2020-12-27 14:34 UTC, ilyamore88 approved these changes
👍

2020-12-29 12:18 UTC, neSpecc requested changes

2020-12-29 12:18 UTC, neSpecc commented on src/protocol/types/index.ts
> +};
не понятно, почему это лежит в папке `protocol`? это же часть бизнес-логики приложения

2020-12-29 12:18 UTC, neSpecc commented on src/protocol/index.ts
> +          case 'workspace-updated':
аналогично, почему это лежит в папке protocol? и какую смысловую нагрузку несет эта папка? Что в ней будет храниться?

2020-12-29 19:49 UTC, kebyo commented on src/protocol/index.ts
> +          case 'workspace-updated':
Я думал в protocol будет лежать типы для общения с апи и CTProtoClient, который можно импортировать из protocol и делать запросы

2020-12-30 06:56 UTC, neSpecc requested changes

2020-12-30 06:56 UTC, neSpecc commented on .env.example
> +VUE_APP_TOKEN=
неудачное название. Что за токен?

2020-12-30 06:56 UTC, neSpecc commented on src/utils/transport/types/index.ts
> +  | GetWorkspacesResponse;
снова бизнес-логика в утилзах. Утилита — это абстрактный вспомогательный модуль

2020-12-30 11:32 UTC, kebyo commented on .env.example
> +VUE_APP_TOKEN=
Замена для JWT токена пока что

2020-12-30 11:36 UTC, kebyo commented on src/utils/transport/types/index.ts
> +  | GetWorkspacesResponse;
Тогда по сути у транспорта не должно быть типов тогда. Точнее типы в utils, потому что во всех типах есть бизнес-логика. У `authorize` свой payload, у `get-workspaces` свой payload и type. Может вынести все типы в src/types/api?

2020-12-30 13:47 UTC, neSpecc commented on .env.example
> +TOKEN=
все еще непонятное название. Токенов может быть сколько угодно, это слово само по себе ничего не значит.

2020-12-30 13:47 UTC, neSpecc commented on src/utils/transport/types/index.ts
> +  | GetWorkspacesResponse;
это не типы транспорта, а типы конкретного приложения. `src/types/api` гораздо лучше

2020-12-30 14:11 UTC, neSpecc approved these changes

2020-12-30 14:19 UTC, talyguryn requested changes
![image](https://user-images.githubusercontent.com/15259299/103356925-08b3a080-4ac3-11eb-8215-4d26cbb5a385.png)

please delete this file from request. we use yarn.lock

2020-12-30 14:21 UTC, talyguryn approved these changes

2020-12-30 14:24 UTC, merged