Feature/real workspace data
codex-team/devops-toolbox-app pull request #29
Opened 2021-01-12 18:21 UTC by kebyo

Проблема: не знаю как получить доступ к хранилищу, которое используется в vue приложении, из основного процесса.

Решения, которые я пытался использовать, находятся в `src/background.ts в onAuth`
 
(Картинка относится к 2 пункту)
![image](https://user-images.githubusercontent.com/64841603/104355604-f94d4200-551b-11eb-8219-8be9d8291374.png)

2021-01-13 17:20 UTC, ilyamore88 commented on src/background.ts
> +const transprot = new CTProtoClient<AuthorizeMessagePayload, DevopsToolboxAuthData, ApiRequest, ApiResponse, ApiUpdate>({
```suggestion
const transport = new CTProtoClient<AuthorizeMessagePayload, DevopsToolboxAuthData, ApiRequest, ApiResponse, ApiUpdate>({
```

2021-01-15 19:55 UTC, ilyamore88 requested changes
Откатить изменения с путями.

2021-01-15 19:55 UTC, ilyamore88 commented on src/App.vue
>        name: 'CodeX',
Лишняя переменная

2021-01-15 19:55 UTC, ilyamore88 commented on src/background.ts
> +    const transprot = new CTProtoClient<AuthorizeMessagePayload, DevopsToolboxAuthData, ApiRequest, ApiResponse, ApiUpdate>({
```suggestion
    const transport = new CTProtoClient<AuthorizeMessagePayload, DevopsToolboxAuthData, ApiRequest, ApiResponse, ApiUpdate>({
```

2021-01-15 19:55 UTC, ilyamore88 commented on src/background.ts
> +    // resizable: false,
Зачем закомментировал это?

2021-01-15 19:55 UTC, ilyamore88 commented on src/components/Server.vue
> +        // }
🤨

2021-01-15 19:55 UTC, ilyamore88 commented on src/components/Server.vue
> +      console.log(services);
Log

2021-01-15 19:55 UTC, ilyamore88 commented on src/store/index.ts
> +      const index = state.workspaces.findIndex(w => workspace.name === w.name);
Почему ты сравниваешь по `name`, а не по `_id`?

2021-01-15 19:55 UTC, ilyamore88 commented on src/store/index.ts
> +      const index = state.workspaces.findIndex(w => workspace.name === w.name);
`name` не уникальное поле.

2021-01-15 19:56 UTC, ilyamore88 commented on src/background.ts
> +    const transprot = new CTProtoClient<AuthorizeMessagePayload, DevopsToolboxAuthData, ApiRequest, ApiResponse, ApiUpdate>({
И нужен ли здесь eslint-disable

2021-01-16 12:20 UTC, neSpecc requested changes

2021-01-16 12:20 UTC, neSpecc commented on src/components/Service.vue
> +    type: {
не описаны свойства

2021-01-16 12:20 UTC, neSpecc commented on src/components/Workspace.vue
> +    name: {
не описаны свойства

2021-01-16 12:20 UTC, neSpecc commented on src/store/index.ts
> +    workspacesUpdate(state, workspaces: Workspace[]) {
нет доков

2021-01-16 12:20 UTC, neSpecc commented on src/types/project.ts
> +     Project name
```suggestion
    * Project name
```

2021-01-16 12:20 UTC, neSpecc commented on src/App.vue
> +    ipcRenderer.on('successful-authorization', (event, data) => {
а зачем два разных события, если они одинаковые по сути?

2021-01-16 12:20 UTC, neSpecc commented on src/App.vue
> +    actualWorkspaces(): IWorkspace[] {
не описано

2021-01-18 16:43 UTC, kebyo commented on src/background.ts
> +    // resizable: false,
Хотел чекнуть логи в браузере

2021-01-18 16:43 UTC, kebyo commented on src/background.ts
> +    const transprot = new CTProtoClient<AuthorizeMessagePayload, DevopsToolboxAuthData, ApiRequest, ApiResponse, ApiUpdate>({
Не нужен. Убрал

2021-01-18 17:26 UTC, kebyo commented on src/App.vue
> +    ipcRenderer.on('successful-authorization', (event, data) => {
Ну тут скорее всего некорректное название события. Тут должно быть `'workspaces-update'` - обновление списка воркспейсов. Для авторизации или запроса `'get-workspaces'`. А `'workspace-update'` - для обновления от агента. Я сделал отдельные методы, потому что подумал, что запросы от агента происходят чаще, чем другие запросы и часто доставать все воркспейсы клиента  - дорого. Лучше отправлять инфу об одном воркспейсе и на клиенете найти его и обновить.

2021-01-19 18:01 UTC, neSpecc commented on src/App.vue
> +      :key="workspace.name"
имя – неуникальное значение, лучше использовать id

2021-01-19 18:01 UTC, neSpecc commented on src/App.vue
>        name: 'CodeX',
это еще используется?

2021-01-19 18:01 UTC, neSpecc commented on src/App.vue
> +     * Actual user workspace list
описание повторяет название

2021-01-19 20:36 UTC, kebyo commented on src/App.vue
>        name: 'CodeX',
Используется только `Workspace`

2021-01-20 18:34 UTC, neSpecc commented on src/store/index.ts
> +      const index = state.workspaces.findIndex(w => workspace._id === w._id);
нет проверки на несуществующий индекс

2021-01-21 10:24 UTC, neSpecc approved these changes

2021-01-21 10:27 UTC, ilyamore88 approved these changes

2021-01-21 10:33 UTC, merged