[Feature] Correct ssh connection
codex-team/devops-toolbox-app pull request #30
Opened 2021-01-24 19:29 UTC by ilyamore88

Gets data about ssh connection from api and uses it for opening correct ssh connection.

2021-01-24 20:23 UTC, neSpecc requested changes

2021-01-24 20:23 UTC, neSpecc commented on src/components/Server.vue
> +      type: Object || null,
надо типизировать объект

2021-01-25 09:04 UTC, neSpecc commented on src/components/Workspace.vue
> +      type: Array,
не указан тип

2021-01-25 16:59 UTC, neSpecc approved these changes

2021-01-25 17:11 UTC, kebyo approved these changes

2021-01-25 17:15 UTC, merged