Window positioning fix
codex-team/devops-toolbox-app pull request #33
Opened 2021-01-31 18:15 UTC by fabled228

closes #16

2021-02-01 19:04 UTC, ilyamore88 commented
![image](https://user-images.githubusercontent.com/37909603/106505436-5fa10100-64d9-11eb-8062-fd4f068b6e6d.png)
Если панель справа, приложение вылетает.

2021-02-01 19:04 UTC, ilyamore88 commented
![image](https://user-images.githubusercontent.com/37909603/106505500-721b3a80-64d9-11eb-8a1d-7b6cb395b15b.png)
Если слева.

2021-02-01 19:05 UTC, ilyamore88 commented
![image](https://user-images.githubusercontent.com/37909603/106505542-83fcdd80-64d9-11eb-8fdd-513778b183dc.png)
Если вверху.

2021-02-09 15:29 UTC, neSpecc requested changes

2021-02-09 15:29 UTC, neSpecc commented on src/utils/calcWindowBounds.ts
> +/**
метод не описан

2021-02-09 15:29 UTC, neSpecc commented on src/background.ts
> +      win.setBounds(calcWindowBounds(getWindowPosition(tray), win, bounds, tray));
почему такая вложенность? плохо читается, надо присвоить в переменные

2021-02-09 15:29 UTC, neSpecc commented on src/utils/calcWindowBounds.ts
> +  const topIndent = 10;
надо описать такие константы

2021-02-09 15:29 UTC, neSpecc commented on src/utils/getWindowPosition.ts
> +const trayToScreenRects = (tray: Tray): [Rectangle, Rectangle] => {
почему это константа с анонимной стрелочной функцией, а не обычная именованная function? и где док к ней

2021-02-09 15:29 UTC, neSpecc commented on src/utils/getWindowPosition.ts
> +type TaskbarLocation = 'top' | 'bottom' | 'left' | 'right';
не описано

2021-02-09 15:29 UTC, neSpecc commented on src/utils/getWindowPosition.ts
> +export type WindowPosition = 'trayCenter'
не описано

2021-02-09 16:40 UTC, fabled228 commented on src/utils/getWindowPosition.ts
> +const trayToScreenRects = (tray: Tray): [Rectangle, Rectangle] => {
а почему константой не подходит?

2021-02-09 16:52 UTC, neSpecc commented on src/utils/getWindowPosition.ts
> +const trayToScreenRects = (tray: Tray): [Rectangle, Rectangle] => {
а зачем? у стрелочных функций другая задача. Обычная функция будем иметь название, так удобнее дебажить.  Оно будет отображаться в стектрейсе.

2021-02-09 17:47 UTC, ilyamore88 approved these changes

2021-02-09 18:08 UTC, neSpecc approved these changes

2021-02-09 18:08 UTC, merged