Feature/auto launch
codex-team/devops-toolbox-app pull request #35
Opened 2021-02-01 21:09 UTC by kebyo

Closes #24

2021-02-02 10:23 UTC, ilyamore88 commented on src/utils/autolaunch.ts
> +    path: '/Applications/DevOps Toolbox.app',
Путь на Windows не будет отличаться разве?

2021-02-02 10:34 UTC, talyguryn requested changes

2021-02-02 10:34 UTC, talyguryn commented on src/utils/autolaunch.ts
> +    path: '/Applications/DevOps Toolbox.app',
путь к файлу на маке может быть другим. на винде там вообще все иначе будет

надо вызвать функцию, которая даст путь к приложению
https://github.com/talyguryn/ssh-quick-connect/blob/alpha/src/auto-launch.js#L7

2021-02-02 10:34 UTC, talyguryn commented on src/utils/autolaunch.ts
> +    name: 'DevOps Toolbox',
имя тоже лучше динамически получать с помощью методов электрона

2021-02-02 10:34 UTC, talyguryn commented on src/utils/autolaunch.ts
> +  const Toolbox = new AutoLaunch({
это все-таки не тулбокс

2021-02-02 10:34 UTC, talyguryn commented on src/utils/autolaunch.ts
> +  Toolbox.isEnabled()
странная логика, конечно, тут происходит. а нет желания добавить возможность тоглить это состояние, чтобы потом можно было где-то в приложении добавить пункт с настройками?

2021-02-05 10:16 UTC, talyguryn approved these changes
если не считать форсирования автозапуска, то все ок. надеюсь в следующих обновлениях будет возможность отключить автозапуск в каких-нибудь настройках приложения

2021-02-05 16:08 UTC, ilyamore88 approved these changes

2021-02-06 22:41 UTC, talyguryn approved these changes

2021-02-07 09:33 UTC, merged