Fix/window opening
codex-team/devops-toolbox-app pull request #37
Opened 2021-02-05 21:45 UTC by fabled228

2021-02-05 21:53 UTC, kebyo approved these changes

2021-02-05 22:43 UTC, ilyamore88 requested changes
Протестирую завтра

2021-02-05 22:43 UTC, ilyamore88 commented on src/utils/isClickOnTray.ts
> + *  Returns if click was on tray
```suggestion
 * Returns true if click was on tray
```

2021-02-05 22:43 UTC, ilyamore88 commented on src/utils/isClickOnTray.ts
> +  return (trayBounds.x > cursorBounds.x || trayBounds.x + trayBounds.width < cursorBounds.x || trayBounds.y > cursorBounds.y || trayBounds.y + trayBounds.height < cursorBounds.y);
Надо бы это условие разбить хотя бы на несколько строк. Совсем нечитаемо.

2021-02-05 22:43 UTC, ilyamore88 commented on src/background.ts
> +  });
Стоит добавить описание

2021-02-06 08:02 UTC, ilyamore88 approved these changes

2021-02-08 16:31 UTC, merged