Feature/prototype
codex-team/devops-toolbox-app pull request #4
Opened 2020-11-19 15:08 UTC by fabled228

Vue prototype added

2020-11-19 15:26 UTC, neSpecc requested changes

2020-11-19 15:26 UTC, neSpecc commented on src/App.vue
> +export default defineComponent({
```suggestion
export default Vue.extend({
```

2020-11-19 15:26 UTC, neSpecc commented on src/App.vue
> +import { defineComponent } from 'vue';
```suggestion
import vue from 'vue';
```

2020-11-19 15:26 UTC, neSpecc commented on src/App.vue
> +  background-color: #294068;
пора делать файл с переменными и вынести туда цвета

2020-11-19 15:26 UTC, neSpecc commented on src/components/Project.vue
> +    :style="{ color: (status ? '#cadafb' : '#f74f4f') }"
Лучше добавить модификаторы к классу `project` (`project--status-ok`, `project--status-warning`)и перенести цвета в CSS (а там их взять их переменных)

2020-11-19 15:26 UTC, neSpecc commented on src/components/Project.vue
> +      :class="'project-status-'+(status ? 'green' : 'red')"
а тут уже можно не делать модификатор, тк статус можно взять от project:

```pcss
.project{
  &--status-warning {
    // ..
  }

  &__status {
   // ...
  }

  &--status-wraning &__status {
    // ...
  }
}
```

2020-11-19 15:26 UTC, neSpecc commented on src/components/Project.vue
> +      class="project-status"
по БЭМу это элемент блока project. То есть будет `project__status`

2020-11-19 15:26 UTC, neSpecc commented on src/components/Project.vue
> +    name: {
свойства не описаны

2020-11-19 15:26 UTC, neSpecc commented on src/components/Project.vue
> +  background-color: #08ff84;
все цвета надо взять из переменных

2020-11-19 15:26 UTC, neSpecc commented on src/components/Server.vue
> +      <div class="bash">
иконку, я думаю, лучше взять как svg из макета.

2020-11-19 15:26 UTC, neSpecc commented on src/components/Server.vue
> +        ⌘{{ hotkey }}
это лучше взять из `computed`  свойства, тк там надо добавить проверку на ОС:
на винде и линуксе это будет `CTRL+hotkey`, а на маке `⌘+hotkey`

2020-11-19 15:26 UTC, neSpecc commented on src/components/WorkspaceHeader.vue
> +    <div class="status">
бэйдж надо вынести в отдельный компонент

2020-11-20 14:09 UTC, neSpecc commented on src/App.vue
> +export default defineComponent({
хотя я не знаю как во vue3 правильнее

2020-11-20 14:11 UTC, nikmel2803 reviewed
- шрифты с макетом не совпадают
- иконка с терминалом тоже

2020-11-20 14:13 UTC, nikmel2803 reviewed
подключить иконку в статус баре из макета

2020-11-20 14:18 UTC, nikmel2803 commented on src/App.vue
> +export default defineComponent({
тут всё ок
https://v3.vuejs.org/guide/typescript-support.html#defining-vue-components

2020-11-20 17:57 UTC, fabled228 commented on src/components/Server.vue
> +      <div class="bash">
@neSpecc в макете нет такой иконки

2020-11-20 20:18 UTC, fabled228 commented on src/components/WorkspaceHeader.vue
> +    <div class="status">
@neSpecc ты вроде говорил, что мы пока убираем бейдж. Мне его выносить или убирать?

2020-11-20 20:32 UTC, neSpecc commented on src/components/WorkspaceHeader.vue
> +    <div class="status">
убирай

2020-11-20 20:37 UTC, fabled228 commented on src/components/WorkspaceHeader.vue
> +    <div class="status">
@neSpecc по поводу шрифта, использовать робото или те, названия которых указаны в макете?

2020-11-20 21:37 UTC, fabled228 commented on src/components/Server.vue
> +        ⌘{{ hotkey }}
@neSpecc лучше проверять, экспортируя через электрон или через браузерный навигатор?

2020-11-20 21:43 UTC, neSpecc commented on src/components/WorkspaceHeader.vue
> +    <div class="status">
Cорри, я забыл, что там не Roboto, а [системные шрифты](https://css-tricks.com/snippets/css/system-font-stack/). Это упрощает дело 

https://css-tricks.com/snippets/css/system-font-stack/

```css
body {
  font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif;
}
```

2020-11-21 12:51 UTC, neSpecc requested changes

2020-11-21 12:51 UTC, neSpecc commented on src/App.vue
> +  padding: 0 1px 2px;
```suggestion
```

2020-11-21 12:54 UTC, neSpecc approved these changes

2020-11-22 15:38 UTC, nikmel2803 commented on src/components/WorkspaceHeader.vue
> +  &-image {
Если по БЭМ, то надо ведь __image

2020-11-22 15:38 UTC, nikmel2803 commented on src/components/Server.vue
> +      <div class="bash">
надо попросить Петю экспортировать svg
Иконка всё ещё не такая, как в макете

2020-11-24 18:37 UTC, nikmel2803 approved these changes

2020-11-24 18:38 UTC, merged