Feature/add terminal opening
codex-team/devops-toolbox-app pull request #5
Opened 2020-11-24 16:03 UTC by Xemka

1. Добавил открытие терминала по нажатию на иконку сервера

2020-11-27 18:05 UTC, ilyamore88 requested changes

2020-11-27 18:05 UTC, ilyamore88 commented on actions/session.ts
> +const session = function (command: string): void {
Нет доков

2020-11-27 18:05 UTC, ilyamore88 commented on actions/session.ts
> +const session = function (command: string): void {
+ можно сразу `export dafault function session()`

2020-11-27 18:05 UTC, ilyamore88 commented on package.json
> +    "@types/node": "^14.14.9",
А для чего типы добавлял?

2020-11-27 18:05 UTC, ilyamore88 commented on actions/session.ts
> +    childProcess.exec(`start cmd.exe /K ${command}`);
Было бы круто в будущем сделать выбор дефолтной консоли, чтобы в powershell открывать

2020-11-27 18:05 UTC, ilyamore88 commented on actions/session.ts
> +    const terminal = 'gnome-terminal';
А если у меня не GNOME?

2020-12-01 17:26 UTC, ilyamore88 commented
На винде открывается 👍

2020-12-01 18:03 UTC, Xemka commented on package.json
> +    "@types/node": "^14.14.9",
Наверное пытался какую-то ошибку пофиксить. Но все работает и без этого. Уберу.

2020-12-01 18:17 UTC, ilyamore88 commented on src/components/Server.vue
> +   }
Что-то с выравниванием

2020-12-01 18:29 UTC, ilyamore88 commented on src/components/Server.vue
> +    openTerminal(): void {
Нет дока

2020-12-01 18:30 UTC, ilyamore88 commented on src/components/Server.vue
> +   }
```suggestion
  }
```

2020-12-01 18:34 UTC, Xemka commented on src/components/Server.vue
> +   }
закрывающая } автоматически ставится под :, не под &

2020-12-01 19:06 UTC, ilyamore88 approved these changes
👍

2020-12-02 13:40 UTC, neSpecc commented on actions/session.ts
> +  if (process.platform == 'win32') {
давай уж switch тогда

2020-12-02 18:08 UTC, nikmel2803 approved these changes

2020-12-02 18:08 UTC, nikmel2803 commented on src/components/Server.vue
> +  cursor: pointer;
выравнивание

2020-12-02 18:09 UTC, merged