Menu added
codex-team/devops-toolbox-app pull request #7
Opened 2020-11-27 18:20 UTC by fabled228

2020-11-27 18:28 UTC, neSpecc requested changes

2020-11-27 18:28 UTC, neSpecc commented on src/index.ts
> +  const template = [
сразу выноси код в соответсвующие методы, не нужно все писать в одной фукнции

2020-12-01 21:40 UTC, neSpecc commented on src/index.ts
> + *  Creating menu
```suggestion
 *  Creates the system menu that will be displayed by right-arrow click on the app icon.
```

2020-12-01 21:41 UTC, neSpecc approved these changes

2020-12-02 13:08 UTC, ilyamore88 approved these changes
На винде ок 👍

2020-12-02 13:17 UTC, merged